### ISSUE TITLE
Error while loading the module - but it works..

### ISSUE THREAD

**Issue by thecobra666** [DCSBL/ha-homewizard-energy#25]
021-04-19 13:29:33	stdout	ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.system_health'[0m
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-04-19 13:29:33	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33	stdout	  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-04-19 13:29:33	stdout	    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33	stdout	    cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33	stdout	    platform = integration.get_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33	stdout	Traceback (most recent call last):
2021-04-19 13:29:33	stdout	[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/system_health.py
2021-04-19 13:29:33	stdout	ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.logbook'[0m
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-04-19 13:29:33	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33	stdout	  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-04-19 13:29:33	stdout	    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33	stdout	    cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33	stdout	    platform = integration.get_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33	stdout	Traceback (most recent call last):
2021-04-19 13:29:33	stdout	[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/logbook.py
2021-04-19 13:29:33	stdout	ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.group'[0m
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-04-19 13:29:33	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33	stdout	  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-04-19 13:29:33	stdout	    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33	stdout	    cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33	stdout	    platform = integration.get_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33	stdout	Traceback (most recent call last):
2021-04-19 13:29:33	stdout	[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/group.py
2021-04-19 13:29:33	stdout	ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.media_source'[0m
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-04-19 13:29:33	stdout	  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-04-19 13:29:33	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33	stdout	  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-04-19 13:29:33	stdout	    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33	stdout	    cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33	stdout	    platform = integration.get_platform(platform_name)
2021-04-19 13:29:33	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33	stdout	Traceback (most recent call last):
2021-04-19 13:29:32	stdout	[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/media_source.py

**Comment by DCSBL** [comment]
Thank you for sharing.
Please re-open a new issue while filling out the questions template, or give me at least some more context about your environment.
