### ISSUE TITLE
Error while starting up Home Assistant

### ISSUE THREAD

**Issue by thecobra666** [DCSBL/ha-homewizard-energy#26]
**Describe the bug**
021-04-19 13:29:33 stdout ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.system_health'�[0m
2021-04-19 13:29:33 stdout File "", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33 stdout File "", line 991, in _find_and_load
2021-04-19 13:29:33 stdout File "", line 1014, in _gcd_import
2021-04-19 13:29:33 stdout return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33 stdout File "/usr/local/lib/python3.8/importlib/init.py", line 127, in import_module
2021-04-19 13:29:33 stdout return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33 stdout cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33 stdout platform = integration.get_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33 stdout Traceback (most recent call last):
2021-04-19 13:29:33 stdout �[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/system_health.py
2021-04-19 13:29:33 stdout ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.logbook'�[0m
2021-04-19 13:29:33 stdout File "", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33 stdout File "", line 991, in _find_and_load
2021-04-19 13:29:33 stdout File "", line 1014, in _gcd_import
2021-04-19 13:29:33 stdout return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33 stdout File "/usr/local/lib/python3.8/importlib/init.py", line 127, in import_module
2021-04-19 13:29:33 stdout return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33 stdout cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33 stdout platform = integration.get_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33 stdout Traceback (most recent call last):
2021-04-19 13:29:33 stdout �[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/logbook.py
2021-04-19 13:29:33 stdout ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.group'�[0m
2021-04-19 13:29:33 stdout File "", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33 stdout File "", line 991, in _find_and_load
2021-04-19 13:29:33 stdout File "", line 1014, in _gcd_import
2021-04-19 13:29:33 stdout return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33 stdout File "/usr/local/lib/python3.8/importlib/init.py", line 127, in import_module
2021-04-19 13:29:33 stdout return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33 stdout cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33 stdout platform = integration.get_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33 stdout Traceback (most recent call last):
2021-04-19 13:29:33 stdout �[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/group.py
2021-04-19 13:29:33 stdout ModuleNotFoundError: No module named 'custom_components.homewizard_energy_p1.media_source'�[0m
2021-04-19 13:29:33 stdout File "", line 973, in _find_and_load_unlocked
2021-04-19 13:29:33 stdout File "", line 991, in _find_and_load
2021-04-19 13:29:33 stdout File "", line 1014, in _gcd_import
2021-04-19 13:29:33 stdout return _bootstrap._gcd_import(name[level:], package, level)
2021-04-19 13:29:33 stdout File "/usr/local/lib/python3.8/importlib/init.py", line 127, in import_module
2021-04-19 13:29:33 stdout return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
2021-04-19 13:29:33 stdout cache[full_name] = self._import_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
2021-04-19 13:29:33 stdout platform = integration.get_platform(platform_name)
2021-04-19 13:29:33 stdout File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
2021-04-19 13:29:33 stdout Traceback (most recent call last):
2021-04-19 13:29:32 stdout �[31m2021-04-19 15:29:32 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing homewizard_energy/media_source.py

**To Reproduce**
Just installed the custom module and started up home assistant. Error pops-up in the home assistant log but the integration works.. 

**Environment (please complete the following information):**
 - Integration version: latest on github
 - Home Assistant version: latest docker container 2021.4.4?

**Comment by DCSBL** [comment]
Thank you, will look into it 👍

**Comment by DCSBL** [comment]
The component name is `custom_components.homewizard_energy`, not `custom_components.homewizard_energy_p1`. I do no know why it says that. Do you have something like `homewizard_energy_p1` in your configuration.yml or in your config folder?

**Comment by thecobra666** [comment]
> The component name is `custom_components.homewizard_energy`, not `custom_components.homewizard_energy_p1`. I do not know why it says that. Do you have something like `homewizard_energy_p1` in your configuration.yml or in your config folder?

You may close the issue. The component folder was homewizard_energy_P1 and I changed it to homewizard_energy. Now the error message is gone.

**Comment by DCSBL** [comment]
🎉 awesome
Is this something that you did because it was stated somewhere, or was it simply a mistake from yourself that you called it `homewizard_energy_p1`?

**Comment by thecobra666** [comment]
> 🎉 awesome
> Is this something that you did because it was stated somewhere, or was it simply a mistake from yourself that you called it `homewizard_energy_p1`?

I saw it on the forums from home assistant https://community.home-assistant.io/t/custom-component-homewizard-energy-wifi-p1-meter/227441/16
