### ISSUE TITLE
Integration can't connect or add entities 

### ISSUE THREAD

**Issue by stefdewilde** [DCSBL/ha-homewizard-energy#30]
I get the following error (see below)
I had to readd my P1 meter because I changed my wifi. I can only add it through the auto discovery, can't add it through manual way. It works fine on the Energy app. I also get the reply from the Api check..

Logger: homeassistant.components.sensor
Source: custom_components/homewizard_energy/sensor.py:136
Integration: Sensor (documentation, issues)
First occurred: 20:09:46 (2 occurrences)
Last logged: 20:09:51

Error while setting up homewizard_energy platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/homewizard_energy/sensor.py", line 128, in async_setup_entry
    await energy_api.initialize()
  File "/usr/local/lib/python3.8/site-packages/aiohwenergy/hwenergy.py", line 50, in initialize
    await self.update()
  File "/usr/local/lib/python3.8/site-packages/aiohwenergy/hwenergy.py", line 54, in update
    status, response = await self.request('get', 'api')
  File "/usr/local/lib/python3.8/site-packages/aiohwenergy/hwenergy.py", line 96, in request
    raise RequestError(
aiohwenergy.errors.RequestError: Error requesting data from 192.168.0.81: Connector is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/homewizard_energy/sensor.py", line 136, in async_setup_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None

**Comment by DCSBL** [comment]
Weird, let's see.
- Can you tell me the version of the integration, and have you installed it through HACS or manually?
- What do you mean with 'can't add it through the manual way'? Is this option unavailable or broken?
-It seems that your HA has trouble accessing your P1 meter. Can you verify that the IP address is correct? You can try to access http://192.168.0.81/api/v1/data and see if you get some JSON.
