### ISSUE TITLE
Core and custom integration can't be used at the same time

### ISSUE THREAD

**Issue by DCSBL** [DCSBL/ha-homewizard-energy#76]
**Describe the bug**
If you run the custom and core version at the same time you get a message like:
```
Logger: homeassistant.config_entries
Source: components/homewizard/coordinator.py:34
First occurred: 11:28:23 (2 occurrences)
Last logged: 11:30:45

Error setting up entry P1 meter (**REDACTED**) for homewizard
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/homewizard/init.py", line 24, in async_setup_entry
coordinator = Coordinator(hass, entry.data[CONF_IP_ADDRESS])
File "/usr/src/homeassistant/homeassistant/components/homewizard/coordinator.py", line 34, in init
self.api = aiohwenergy.HomeWizardEnergy(host, clientsession=session)
TypeError: init() got an unexpected keyword argument 'clientsession'
```

**Expected behavior**

As I want you to be able to run both systems at the same time while migrating, I will try to fix this.

**Comment by DCSBL** [comment]
Fixed by #78
